---
services:
  polishrr:
    image: ghcr.io/legromorph/polishrr:latest
    container_name: polishrr
    environment:
      - CRON_SCHEDULE=0 * * * *
      - TZ=America/Los_Angeles
    volumes:
      - /path/to/config:/config # place your .env file in here
      
